from .models import Game


def insert_games():
    games = [
        {'id': 1, 'name': 'Elden Ring', 'description': 'Action RPG', 'price': 50,
         'img': 'https://cdn.vox-cdn.com/thumbor/jU4OWAnNWXqIiyzHrpuKAJdqPjQ=/0x0:1920x1096/1000x1000/filters:focal(960x548:961x549)/cdn.vox-cdn.com/uploads/chorus_asset/file/24076850/elden_ring_bandai_namco.jpg',
         'metascore': 96, 'age': 16,
         'about_game': 'це рольова гра, розроблена FromSoftware у співпраці з Джорджем Мартіном. Гравці занурюються у величезний відкритий світ, наповнений загадками, епічними боями та різноманітними істотами.',
         'platform': 'PC / Xbox one / PS4 / Xbox series / PS5'},
        {'id': 2, 'name': "Baldur's Gate 3", 'description': 'Western RPG', 'price': 70,
         'img': 'https://cdn.vox-cdn.com/thumbor/PbKRNpSN66NIjMMWdXJ7znhQR3Q=/0x0:1920x1280/1000x1000/filters:focal(347x539:348x540)/cdn.vox-cdn.com/uploads/chorus_asset/file/24828421/bg3.png',
         'metascore': 96, 'age': 18,
         'about_game': 'це легендарна рольова гра, дія якої розгортається у всесвіті Dungeons & Dragons. Гравці беруть на себе роль героя, який подорожує по світу, зустрічає союзників, бореться з ворогами та розкриває таємниці свого походження.',
         'platform': 'PC / Xbox one / PS4 / Xbox series / PS5'},
        {'id': 3, 'name': 'The Witcher 3: Wild Hunt', 'description': 'Action RPG', 'price': 26,
         'img': 'https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/kh4MUIuMmHlktOHar3lVl6rY.png',
         'metascore': 94, 'age': 18,
         'about_game': 'це епічна рольова гра, в якій гравці керують відьмаком Ґеральтом з Рівії. У грі поєднано захоплюючий сюжет, глибоку бойову систему та великий відкритий світ, наповнений пригодами, монстрами та складними моральними виборами.',
         'platform': 'PC / Xbox one / PS4 / Xbox series / PS5 / Nintendo Switch'},
        {'id': 4, 'name': 'God of War: Ragnarok', 'description': 'Action Adventure', 'price': 60,
         'img': 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png',
         'metascore': 94, 'age': 18,
         'about_game': 'це продовження епічної саги про Кратоса і його сина Атрея, що занурює гравців у світ скандинавської міфології. У грі на них чекають масштабні битви з богами, неймовірні пригоди та глибокий емоційний сюжет, що розкриває складні стосунки між батьком і сином на тлі наближення кінця світу — Рагнароку.',
         'platform': 'PC / PS4 / PS5'}, {'id': 5, 'name': 'Resident Evil 4', 'description': 'Survival', 'price': 30,
                                         'img': 'https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/EVWyZD63pahuh95eKloFaJuC.png',
                                         'metascore': 93, 'age': 18,
                                         'about_game': 'це оновлена версія культового хорору з новою графікою та покращеними механіками. Гра переносить гравців у страшний світ, де головному герою доведеться боротися за виживання проти зомбі та інших чудовиськ.',
                                         'platform': 'PC / PS4 / PS5 / Xbox Series '},
        {'id': 6, 'name': 'Final Fantasy VII Rebirth', 'description': 'Action RPG', 'price': 70,
         'img': 'https://assets-prd.ignimgs.com/2024/01/19/ff7rebirth-1705691603436.jpg', 'metascore': 92, 'age': 16,
         'about_game': 'друга частина римейку легендарної гри, яка продовжує історію Клауда і його товаришів у світі, що знаходиться на межі катастрофи. Гра вражає своєю графікою, епічними боями та емоційним сюжетом.',
         'platform': 'PS5'}, {'id': 7, 'name': 'Persona 5 Royal', 'description': 'JRPG', 'price': 106,
                              'img': 'https://assets1.ignimgs.com/2020/02/14/persona-5-royal---button-fin-1581716582492.jpg',
                              'metascore': 91, 'age': 16,
                              'about_game': 'розширена версія культової JRPG, що розповідає історію групи підлітків, які протистоять корупції в сучасному Токіо, занурюючись у світи людських сердець. Гра поєднує в собі елементи соціального симулятора та класичної RPG.',
                              'platform': 'PS4 / PS5 / PC / Xbox Series / Nintendo Switch'},
        {'id': 8, 'name': "Marvel's Spider-Man 2", 'description': 'Open-World Action', 'price': 70,
         'img': 'https://image.api.playstation.com/vulcan/ap/rnd/202306/1219/1c7b75d8ed9271516546560d219ad0b22ee0a263b4537bd8.png',
         'metascore': 90, 'age': 16,
         'about_game': 'продовження пригод Людини-павука від Insomniac Games. У цій грі гравці можуть керувати як Пітером Паркером, так і Майлзом Моралесом, досліджуючи Нью-Йорк та борючись з новими небезпечними ворогами.',
         'platform': 'PS5'}, {'id': 9, 'name': 'Destiny 2: The Final Shape', 'description': 'FPS', 'price': 100,
                              'img': 'https://assets-prd.ignimgs.com/2024/06/05/ign-single-cms-81-1717585492908.png',
                              'metascore': 90, 'age': 16,
                              'about_game': 'завершальний розділ епічної саги Destiny 2, що пропонує гравцям захопливі місії, нові рейди та безліч контенту в улюбленому всесвіті. Гравці стикаються з кінцевою загрозою та розкривають найглибші таємниці гри.',
                              'platform': 'PC / PS4 / PS5 / Xbox One / Xbox Series '},
        {'id': 10, 'name': 'The Last of Us Part II Remastered', 'description': 'Survival', 'price': 50,
         'img': 'https://image.api.playstation.com/vulcan/ap/rnd/202312/0117/315718bce7eed62e3cf3fb02d61b81ff1782d6b6cf850fa4.png',
         'metascore': 90, 'age': 18,
         'about_game': 'оновлена версія одного з найвідоміших екшенів у світі відеоігор. Гра розповідає емоційну історію Еллі у світі, що зазнав апокаліпсису, та вражає новим рівнем графіки та деталей.',
         'platform': 'PS5'},
        {'id': 11, 'name': 'Dead Space', 'description': 'Survival horror in a desolate mining starship.', 'price': 50,
         'img': 'https://snworksceo.imgix.net/cml/d61d4ec8-abe7-405f-8bdd-f8fc237a006a.sized-1000x1000.jpeg?w=1000',
         'metascore': 89, 'age': 16,
         'about_game': 'A survival horror game set in a mining starship where you must survive against hostile creatures.',
         'platform': 'PS5 / Xbox series / PC'},
        {'id': 12, 'name': 'Like a Dragon: Infinite Wealth', 'description': 'Epic RPG action with dynamic battles.',
         'price': 40, 'img': 'https://sm.ign.com/ign_nordic/cover/y/yakuza-8/yakuza-8_wu8v.jpg', 'metascore': 89,
         'age': 18, 'about_game': 'An RPG adventure with dynamic combat and a vast world to explore.',
         'platform': 'PC / Xbox series / PS5 / Xbox one / PS4'},
        {'id': 13, 'name': 'Red Matter 2', 'description': 'Dystopian adventure set during a Cold War.', 'price': 30,
         'img': 'https://image.api.playstation.com/vulcan/ap/rnd/202304/1416/45d2a2d3e246d851d45370411a858640ad122f0ebe0ccd3a.png',
         'metascore': 89, 'age': 12,
         'about_game': 'A dystopian adventure involving a mental simulation and a rescue mission in space.',
         'platform': 'PS5 / Xbox series / PC'},
        {'id': 14, 'name': 'Alan Wake II', 'description': 'Survival horror with psychological elements.', 'price': 60,
         'img': 'https://image.api.playstation.com/vulcan/ap/rnd/202305/2420/c3daf3037feb797d9e71b81618e3b5ff3ff1f9609db5a4a2.png',
         'metascore': 89, 'age': 18,
         'about_game': 'A survival horror game focusing on psychological dread and survival.',
         'platform': 'PS5 / Xbox series / PC'}

    ]

    for game in games:
        Game.objects.create(**game)
